apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: llm-service
  labels:
    app: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/wpan36/llm-frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_URL
              value: http://backend.llm-service.svc.cluster.local:8080
            - name: REQUEST_TIMEOUT
              value: "30"
            - name: MAX_CONCURRENCY
              value: "64"
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
