apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: llm-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30080
  type: NodePort