global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend:8081']