name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  BACKEND_IMAGE: llm-backend
  FRONTEND_IMAGE: llm-frontend
  # Only build for linux/amd64 since backend uses CUDA base image
  PLATFORMS: linux/amd64

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------- Backend image --------
      - name: Build & Push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.BACKEND_IMAGE }}:sha-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.BACKEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # -------- Frontend image --------
      - name: Build & Push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.FRONTEND_IMAGE }}:sha-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.FRONTEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "Built images:"
          echo "  $REGISTRY/$IMAGE_OWNER/$BACKEND_IMAGE:sha-${GITHUB_SHA}"
          echo "  $REGISTRY/$IMAGE_OWNER/$FRONTEND_IMAGE:sha-${GITHUB_SHA}"
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            echo "Also tagged ':latest' and pushed to GHCR."
          else
            echo "PR/branch build: images not pushed."
          fi
